server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_db_text?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "000000"
  security:
    remember-me:
      key: xyn
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true

